# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.flowroute_numbers_and_messaging_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.numbers_controller import NumbersController
from .controllers.routes_controller import RoutesController
from .controllers.messages_controller import MessagesController
from .controllers.e911s_controller import E911sController
from .controllers.cnams_controller import CNAMsController


class FlowroutenumbersandmessagingClient(object):

    config = Configuration

    @lazy_property
    def numbers(self):
        return NumbersController()

    @lazy_property
    def routes(self):
        return RoutesController()

    @lazy_property
    def messages(self):
        return MessagesController()

    @lazy_property
    def e911s(self):
        return E911sController()

    @lazy_property
    def cnams(self):
        return CNAMsController()

    def __init__(self,
                 basic_auth_user_name = None,
                 basic_auth_password = None):
        if basic_auth_user_name != None:
            Configuration.basic_auth_user_name = basic_auth_user_name
        if basic_auth_password != None:
            Configuration.basic_auth_password = basic_auth_password
