# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.flowroute_numbers_and_messaging_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.numbers_controller import NumbersController
from .controllers.routes_controller import RoutesController
from .controllers.messages_controller import MessagesController

class FlowroutenumbersandmessagingClient(object):

    config = Configuration

    @lazy_property
    def numbers(self):
        return NumbersController()

    @lazy_property
    def routes(self):
        return RoutesController()

    @lazy_property
    def messages(self):
        return MessagesController()


    def __init__(self, 
                 basic_auth_user_name = None,
                 basic_auth_password = None):
        if basic_auth_user_name != None:
            Configuration.basic_auth_user_name = basic_auth_user_name
        if basic_auth_password != None:
            Configuration.basic_auth_password = basic_auth_password


