# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.account_routes

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class AccountRoutes(object):

    """Implementation of the 'AccountRoutes' model.

    TODO: type model description here.

    Attributes:
        data (list of object): TODO: type description here.
        links (object): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "data" : "data",
        "links" : "links"
    }

    def __init__(self,
                 data=None,
                 links=None):
        """Constructor for the AccountRoutes class"""

        # Initialize members of the class
        self.data = data
        self.links = links


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        data = dictionary.get("data")
        links = dictionary.get("links")

        # Return an object of this model
        return cls(data,
                   links)


