# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.error_84

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import flowroutenumbersandmessaging.models.error_1

class Error84(object):

    """Implementation of the 'Error84' model.

    TODO: type model description here.

    Attributes:
        errors (list of Error1): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "errors" : "errors"
    }

    def __init__(self,
                 errors=None):
        """Constructor for the Error84 class"""

        # Initialize members of the class
        self.errors = errors


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        errors = None
        if dictionary.get("errors") != None:
            errors = list()
            for structure in dictionary.get("errors"):
                errors.append(flowroutenumbersandmessaging.models.error_1.Error1.from_dictionary(structure))

        # Return an object of this model
        return cls(errors)


