# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.links

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class Links(object):

    """Implementation of the 'Links' model.

    TODO: type model description here.

    Attributes:
        self (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "self" : "self"
    }

    def __init__(self):
        """Constructor for the Links class"""

        # Initialize members of the class
        self.self = self


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        self = dictionary.get("self")

        # Return an object of this model
        return cls(self)


