# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.mdr_2

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import flowroutenumbersandmessaging.models.data

class MDR2(object):

    """Implementation of the 'MDR2' model.

    TODO: type model description here.

    Attributes:
        data (Data): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "data" : "data"
    }

    def __init__(self,
                 data=None):
        """Constructor for the MDR2 class"""

        # Initialize members of the class
        self.data = data


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        data = flowroutenumbersandmessaging.models.data.Data.from_dictionary(dictionary.get("data")) if dictionary.get("data") else None

        # Return an object of this model
        return cls(data)


