# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.message

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class Message(object):

    """Implementation of the 'Message' model.

    TODO: type model description here.

    Attributes:
        mfrom (string): TODO: type description here.
        to (string): TODO: type description here.
        body (string): TODO: type description here.
        media_urls (list of string): TODO: type description here.
        is_mms (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mfrom" : "from",
        "to" : "to",
        "body" : "body",
        "media_urls" : "media_urls",
        "is_mms" : "is_mms"
    }

    def __init__(self,
                 mfrom=None,
                 to=None,
                 body=None,
                 media_urls=None,
                 is_mms=None):
        """Constructor for the Message class"""

        # Initialize members of the class
        self.mfrom = mfrom
        self.to = to
        self.body = body
        self.media_urls = media_urls
        self.is_mms = is_mms


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mfrom = dictionary.get("from")
        to = dictionary.get("to")
        body = dictionary.get("body")
        media_urls = dictionary.get("media_urls")
        is_mms = dictionary.get("is_mms")

        # Return an object of this model
        return cls(mfrom,
                   to,
                   body,
                   media_urls,
                   is_mms)


