# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.message_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class MessageTypeEnum(object):

    """Implementation of the 'MessageType' enum.

    TODO: type enum description here.

    Attributes:
        LONGCODE: TODO: type description here.
        TOLLFREE: TODO: type description here.

    """

    LONGCODE = 'longcode'

    TOLLFREE = 'toll-free'

