# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.number_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class NumberTypeEnum(object):

    """Implementation of the 'NumberType' enum.

    TODO: type enum description here.

    Attributes:
        STANDARD: TODO: type description here.
        TOLLFREE: TODO: type description here.
        INUM: TODO: type description here.

    """

    STANDARD = 'standard'

    TOLLFREE = 'tollfree'

    INUM = 'inum'

