# -*- coding: utf-8 -*-

"""
    flowroutenumbersandmessaging.models.route_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class RouteTypeEnum(object):

    """Implementation of the 'RouteType' enum.

    TODO: type enum description here.

    Attributes:
        SIPREG: TODO: type description here.
        HOST: TODO: type description here.
        URI: TODO: type description here.
        NUMBER: TODO: type description here.

    """

    SIPREG = 'sip-reg'

    HOST = 'host'

    URI = 'uri'

    NUMBER = 'number'

